<?php
namespace openadm\admin\themes\adminlte2;

use Yii;
use yii\base\Exception;
use yii\web\AssetBundle as BaseAdminLteAsset;

/**
 * AdminLte AssetBundle
 * @since 0.1
 */
class LayerAsset extends BaseAdminLteAsset
{
    public $sourcePath = '@openadm/admin/themes/adminlte2/assets/libs/layer/';
    public $css = [
        'theme/default/layer.css'
    ];
    public $js = [
        'layer.js',
    ];
    public $depends = [
        'yii\web\JqueryAsset',
    ];

    /**
     * @var string|bool Choose skin color, eg. `'skin-blue'` or set `false` to disable skin loading
     * @see https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#layout
     */
    public $skin = null;

    /**
     * @inheritdoc
     */
    public function init()
    {
        // Append skin color file if specified
        parent::init();
    }

    public function publish($am)
    {
        parent::publish($am); // TODO: Change the autogenerated stub
    }
}
